apiVersion: v1
kind: Pod
metadata:
  name: single-xaod-test
spec:
  restartPolicy: OnFailure
  containers:
    - name: servicex-test
      image: sslhep/servicex_backend_test:latest
      command:
        - "python"
      args: ["tests/single_xaod_test.py", "token", "endpoint"]
      # command:
      #   - "sleep"
      # args: ["3600"]
      resources:
        requests:
          memory: "4Gi"
          cpu: "500m"
        limits:
          memory: "8Gi"
          cpu: "1000m"
