apiVersion: v1
kind: Pod
metadata:
  name: single-xaod-test
spec:
  containers:
    - name: servicex-test
      image: sslhep/servicex_backend_test:latest
      command:
        - "source"
      args: ["test_xaod.sh", "HERE TOKEN"]
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1024Mi"
          cpu: "1000m"
