name: Build Servicex Backend Test image

on:
  push:
    branches:
      - "dev"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v5.6
        with:
          image: sslhep/servicex_backend_test
          tags: latest, ${{ github.sha }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Repository Dispatch
      #   uses: peter-evans/repository-dispatch@v1
      #   with:
      #     token: ${{ secrets.AAAS_GITOPS_DEPLOY_TRIGGER }}
      #     repository: ATLAS-Analytics/deployments
      #     event-type: gitops-aaas-app-trigger
      #     client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
